---
APP_NAME: consul-demo
APP_REPOSITORY: git@bitbucket.org:komuW/consul-demo.git
APP_USER: "{{ ansible_ssh_user }}"
APP_HOME: "/home/{{ APP_USER }}"
APP_DIR: "{{ APP_HOME }}/{{ APP_NAME }}"
APP_VIRTUALENV: "{{ APP_HOME }}/.virtualenvs/{{ APP_NAME }}"
APP_STATIC_DIR: "{{ APP_DIR }}/static"

APP_PORT: 80
GUNICORN_PORT: 3000

RABBIT_MONIT_INTERVAL: 1800 #in seconds
CELERY_WORKERS: 1
GUNICORN_WORKERS: 1

# if deploying to a box where default user is root(eg, Angani), celery wont work --> http://bit.ly/XWqrJS
# in such situatition, set ROOT_USER_BOX: true
ROOT_USER_BOX: false
CELERY_USER: "celery_user"

LOGSENE_APP_TOKEN: "something_here"

ROTATE_INTERVAL: daily
ROTATE_COUNT: 30

HAPROXY_VERSION: "1.6"